package type;

public enum MessageType {
	SEND_ACTIVITY,
	GOT_SCHEDULE,
	GOT_ACTIVITIES,
	DELETE_ITEM,
	DISTRIBUTE_ITEM_LOCATION,
	DISTRIBUTE_ITEM_STATE,
	REGISTER_SUCCESS,
	REGISTER_FAILED,
	RECALCULATE_START,
	RECALCULATE_APPROVEMENT,
	RECALCULATE_FINISH,
	STATIC_TYPES,
	ITEMS_LIST,
	GOT_AGENTS
//	AGENTS_AVAILABILITY,
//	ITEMS_AVAILABILITY
}
