package type;

public enum MessageType {
	SEND_ACTIVITY,
	GOT_SCHEDULE,
	DELETE_ITEM,
	DISTRIBUTE_ITEM_LOCATION,
	DISTRIBUTE_ITEM_STATE,
	REGISTER_SUCCESS,
	REGISTER_FAILED,
	RECALCULATE_START,
	RECALCULATE_FINISH,
	STATIC_TYPES
}
