DROP TABLE APP.ACTIVITYTYPEAGENTS;
DROP TABLE APP.ACTIVITYTYPEITEMS;
DROP TABLE APP.AGENTS;
DROP TABLE APP.ACTIVITIES;
DROP TABLE APP.ITEMS;
DROP TABLE APP.ACTIVITYTYPES;
DROP TABLE APP.AGENTTYPES;
DROP TABLE APP.ITEMTYPES;